from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

DATABASE_DIR = BASE_DIR / "database"
LOGS_DIR = BASE_DIR / "logs"
REPORTS_DIR = BASE_DIR / "reports"
PDF_REPORTS_DIR = REPORTS_DIR / "pdf"
CSV_REPORTS_DIR = REPORTS_DIR / "csv"

EYE_AR_THRESHOLD = 0.25
MOUTH_AR_THRESHOLD = 0.60
HEAD_POSE_THRESHOLD = 25
YOLO_CONFIDENCE_THRESHOLD = 0.50
YOLO_CONFIDENCE = 0.50
MULTI_PERSON_THRESHOLD = 1
YOLO_IOU_THRESHOLD = 0.45
FRAME_SKIP = 2
ALERT_COOLDOWN_SECONDS = 3
FACE_MISSING_SEC = 5
LOOKING_AWAY_ANGLE_DEG = 25
LOOKING_AWAY_PITCH_DEG = 20
LOOKING_AWAY_SEC = 3
CALIBRATION_DURATION_SEC = 3
GAZE_YAW_THRESHOLD_DEG = 22
GAZE_PITCH_THRESHOLD_DEG = 18
GAZE_PITCH_RETURN_THRESHOLD_DEG = 12
POSE_SMOOTHING_FACTOR = 0.35
PHONE_CONFIRM_FRAMES = 2
MULTI_PERSON_CONFIRM_FRAMES = 2
RISK_WEIGHTS = {
	"FACE_MISSING": 20,
	"LOOKING_AWAY": 15,
	"MULTIPLE_PERSON": 30,
	"PHONE_DETECTED": 40,
}
RISK_EVENT_WEIGHTS = RISK_WEIGHTS
RISK_SCORE_CAP = 100