from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

DATABASE_DIR = BASE_DIR / "database"
LOGS_DIR = BASE_DIR / "logs"
REPORTS_DIR = BASE_DIR / "reports"
PDF_REPORTS_DIR = REPORTS_DIR / "pdf"
CSV_REPORTS_DIR = REPORTS_DIR / "csv"

EYE_AR_THRESHOLD = 0.25
MOUTH_AR_THRESHOLD = 0.60
HEAD_POSE_THRESHOLD = 25
YOLO_CONFIDENCE_THRESHOLD = 0.50
YOLO_IOU_THRESHOLD = 0.45
FRAME_SKIP = 2
ALERT_COOLDOWN_SECONDS = 3
FACE_MISSING_SEC = 5